"${HOME}/.gitconfig"                      = "git/gitconfig"
"${HOME}/.config/git/ignore"              = "git/ignore"
"${HOME}/.bashrc"                         = "bash/bashrc"
"${HOME}/.bash_profile"                   = "bash/bash_profile"
"${HOME}/.vimrc"                          = "vim/vimrc"
"${HOME}/.ideavimrc"                      = "jetbrains/ideavimrc"
"${XDG_CONFIG_HOME}/nvim/init.lua"        = "nvim/init.lua"
"${XDG_CONFIG_HOME}/yazi/yazi.toml"       = "yazi/yazi.toml"
"${XDG_CONFIG_HOME}/yazi/keymap.toml"     = "yazi/keymap.toml"
"${XDG_CONFIG_HOME}/wezterm/wezterm.lua"  = "wezterm/wezterm.lua"
"${XDG_CONFIG_HOME}/wezterm/keymap.lua"   = "wezterm/keymap.lua"
"${XDG_CONFIG_HOME}/tmux/tmux.conf"       = "tmux/tmux.conf"
"${XDG_CONFIG_HOME}/gtk-3.0/settings.ini" = "gtk/gtk-3.0-settings.ini"
"${XDG_CONFIG_HOME}/user-dirs.dirs"       = "xdg/user-dirs.dirs"
"${XDG_CONFIG_HOME}/zed/settings.json"    = "zed/settings.json"
"${XDG_CONFIG_HOME}/zed/keymap.json"      = "zed/keymap.json"

[linux]
"${XDG_CONFIG_HOME}/sway/config"          = "sway/config"

[mac]
"${XDG_CONFIG_HOME}/bash/mac.sh"          = "bash/mac.sh"
