[tools]
bat = "latest"
eza = "latest"
fzf = "latest"
ghq = "latest"
ripgrep = "latest"
lazygit = "latest"
yazi = "latest"
lazydocker = "latest"
neovim = "latest"
node = "latest"
github-cli = "latest"
gum = "latest"
pre-commit = "latest"
uv = "latest"
jq = "latest"

[settings]
ignored_config_paths = ["~/Dotfiles/common/.config/mise", "~/Dotfiles/server/.config/mise", "~/Dotfiles/desktop/.config/mise", "~/Dotfiles/mac/.config/mise"]
# experimental = true
# 
# [settings.python]
# uv_venv_auto = true
