alias ..="cd .."
alias ....="cd ../.."
alias so=". ${HOME}/.bashrc"

alias g="git"
alias j="jobs"
alias lg="lazygit"
alias l="eza -al"
alias ls="eza"
alias sl="ls"
alias ll="eza -l"
alias la="eza -a"
alias lla="eza -al"
alias v="nvim"
alias tree="tree -I 'node_modules|__pycache__|.venv|target'"
