alias ..="cd .."
alias ....="cd ../.."
alias so=". ${HOME}/.bashrc"

alias g="git"
alias lg="lazygit"
alias l="eza -al"
alias ls="eza"
alias ll="eza -l"
alias la="eza -a"
alias lla="eza -al"
alias v="nvim"
